name = "PyVistaCompat"
uuid = "402afd0f-a347-4f14-ad4c-abedc99e1684"
authors = ["henrij22 <96132706+henrij22@users.noreply.github.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
